// Map country names to ISO 3166-1 alpha-2 codes
// Then convert to flag emojis using regional indicator symbols
const countryToAlpha2: Record<string, string> = {
	'Afghanistan': 'AF',
	'Albania': 'AL',
	'Algeria': 'DZ',
	'American Samoa': 'AS',
	'Andorra': 'AD',
	'Angola': 'AO',
	'Antigua and Barb.': 'AG',
	'Argentina': 'AR',
	'Armenia': 'AM',
	'Aruba': 'AW',
	'Australia': 'AU',
	'Austria': 'AT',
	'Azerbaijan': 'AZ',
	'Bahamas': 'BS',
	'Bahrain': 'BH',
	'Bangladesh': 'BD',
	'Barbados': 'BB',
	'Belarus': 'BY',
	'Belgium': 'BE',
	'Belize': 'BZ',
	'Benin': 'BJ',
	'Bermuda': 'BM',
	'Bhutan': 'BT',
	'Bolivia': 'BO',
	'Bosnia and Herz.': 'BA',
	'Botswana': 'BW',
	'Brazil': 'BR',
	'British Virgin Is.': 'VG',
	'Brunei': 'BN',
	'Bulgaria': 'BG',
	'Burkina Faso': 'BF',
	'Burundi': 'BI',
	'Cambodia': 'KH',
	'Cameroon': 'CM',
	'Canada': 'CA',
	'Cape Verde': 'CV',
	'Cayman Is.': 'KY',
	'Central African Rep.': 'CF',
	'Chad': 'TD',
	'Chile': 'CL',
	'China': 'CN',
	'Colombia': 'CO',
	'Comoros': 'KM',
	'Congo': 'CG',
	'Costa Rica': 'CR',
	'Croatia': 'HR',
	'Cuba': 'CU',
	'Curaçao': 'CW',
	'Cyprus': 'CY',
	'Czech Rep.': 'CZ',
	'Czechia': 'CZ',
	'Dem. Rep. Congo': 'CD',
	'Democratic Republic of the Congo': 'CD',
	'Denmark': 'DK',
	'Djibouti': 'DJ',
	'Dominica': 'DM',
	'Dominican Rep.': 'DO',
	'Ecuador': 'EC',
	'Egypt': 'EG',
	'El Salvador': 'SV',
	'Equatorial Guinea': 'GQ',
	'Eritrea': 'ER',
	'Estonia': 'EE',
	'Ethiopia': 'ET',
	'Faeroe Is.': 'FO',
	'Falkland Is.': 'FK',
	'Fiji': 'FJ',
	'Finland': 'FI',
	'France': 'FR',
	'French Polynesia': 'PF',
	'Fr. Polynesia': 'PF',
	'Gabon': 'GA',
	'Gambia': 'GM',
	'Georgia': 'GE',
	'Germany': 'DE',
	'Ghana': 'GH',
	'Greece': 'GR',
	'Greenland': 'GL',
	'Grenada': 'GD',
	'Guam': 'GU',
	'Guatemala': 'GT',
	'Guernsey': 'GG',
	'Guinea': 'GN',
	'Guinea-Bissau': 'GW',
	'Guyana': 'GY',
	'Haiti': 'HT',
	'Honduras': 'HN',
	'Hong Kong': 'HK',
	'Hungary': 'HU',
	'Iceland': 'IS',
	'India': 'IN',
	'Indonesia': 'ID',
	'Iran': 'IR',
	'Iraq': 'IQ',
	'Ireland': 'IE',
	'Isle of Man': 'IM',
	'Israel': 'IL',
	'Italy': 'IT',
	'Ivory Coast': 'CI',
	"Côte d'Ivoire": 'CI',
	'Jamaica': 'JM',
	'Japan': 'JP',
	'Jersey': 'JE',
	'Jordan': 'JO',
	'Kazakhstan': 'KZ',
	'Kenya': 'KE',
	'Kiribati': 'KI',
	'Kosovo': 'XK',
	'Kuwait': 'KW',
	'Kyrgyzstan': 'KG',
	'Laos': 'LA',
	'Latvia': 'LV',
	'Lebanon': 'LB',
	'Lesotho': 'LS',
	'Liberia': 'LR',
	'Libya': 'LY',
	'Liechtenstein': 'LI',
	'Lithuania': 'LT',
	'Luxembourg': 'LU',
	'Macao': 'MO',
	'Macedonia': 'MK',
	'Madagascar': 'MG',
	'Malawi': 'MW',
	'Malaysia': 'MY',
	'Maldives': 'MV',
	'Mali': 'ML',
	'Malta': 'MT',
	'Marshall Is.': 'MH',
	'Mauritania': 'MR',
	'Mauritius': 'MU',
	'Mexico': 'MX',
	'Micronesia': 'FM',
	'Moldova': 'MD',
	'Monaco': 'MC',
	'Mongolia': 'MN',
	'Montenegro': 'ME',
	'Morocco': 'MA',
	'Mozambique': 'MZ',
	'Myanmar': 'MM',
	'N. Korea': 'KP',
	'N. Mariana Is.': 'MP',
	'Namibia': 'NA',
	'Nauru': 'NR',
	'Nepal': 'NP',
	'Netherlands': 'NL',
	'New Caledonia': 'NC',
	'New Zealand': 'NZ',
	'Nicaragua': 'NI',
	'Niger': 'NE',
	'Nigeria': 'NG',
	'North Korea': 'KP',
	'North Macedonia': 'MK',
	'Norway': 'NO',
	'Oman': 'OM',
	'Pakistan': 'PK',
	'Palau': 'PW',
	'Palestine': 'PS',
	'Panama': 'PA',
	'Papua New Guinea': 'PG',
	'Paraguay': 'PY',
	'Peru': 'PE',
	'Philippines': 'PH',
	'Poland': 'PL',
	'Portugal': 'PT',
	'Puerto Rico': 'PR',
	'Qatar': 'QA',
	'Romania': 'RO',
	'Russia': 'RU',
	'Rwanda': 'RW',
	'S. Korea': 'KR',
	'S. Sudan': 'SS',
	'Saint Lucia': 'LC',
	'Saint Vincent and the Grenadines': 'VC',
	'Samoa': 'WS',
	'San Marino': 'SM',
	'Saudi Arabia': 'SA',
	'Senegal': 'SN',
	'Serbia': 'RS',
	'Seychelles': 'SC',
	'Sierra Leone': 'SL',
	'Singapore': 'SG',
	'Slovakia': 'SK',
	'Slovenia': 'SI',
	'Solomon Is.': 'SB',
	'Somalia': 'SO',
	'South Africa': 'ZA',
	'South Korea': 'KR',
	'South Sudan': 'SS',
	'Spain': 'ES',
	'Sri Lanka': 'LK',
	'St. Lucia': 'LC',
	'St. Vin. and Gren.': 'VC',
	'Sudan': 'SD',
	'Suriname': 'SR',
	'Swaziland': 'SZ',
	'Sweden': 'SE',
	'Switzerland': 'CH',
	'Syria': 'SY',
	'Taiwan': 'TW',
	'Tajikistan': 'TJ',
	'Tanzania': 'TZ',
	'Thailand': 'TH',
	'Timor-Leste': 'TL',
	'Togo': 'TG',
	'Tonga': 'TO',
	'Trinidad and Tobago': 'TT',
	'Tunisia': 'TN',
	'Turkey': 'TR',
	'Turks and Caicos Is.': 'TC',
	'Turkmenistan': 'TM',
	'Tuvalu': 'TV',
	'U.S. Virgin Is.': 'VI',
	'Uganda': 'UG',
	'Ukraine': 'UA',
	'United Arab Emirates': 'AE',
	'United Kingdom': 'GB',
	'United States': 'US',
	'United States of America': 'US',
	'Uruguay': 'UY',
	'Uzbekistan': 'UZ',
	'Vanuatu': 'VU',
	'Vatican': 'VA',
	'Venezuela': 'VE',
	'Vietnam': 'VN',
	'W. Sahara': 'EH',
	'Yemen': 'YE',
	'Zambia': 'ZM',
	'Zimbabwe': 'ZW'
};

// Convert ISO alpha-2 code to flag emoji
function alpha2ToFlag(code: string): string {
	// Regional indicator symbols start at 0x1F1E6 (A)
	const offset = 0x1F1E6 - 65; // 65 is 'A' in ASCII
	const codePoints = code
		.toUpperCase()
		.split('')
		.map((char) => char.charCodeAt(0) + offset);
	return String.fromCodePoint(...codePoints);
}

export function getCountryFlag(countryName: string): string {
	const code = countryToAlpha2[countryName];
	if (!code) {
		return '🏴‍☠️'; // Generic flag fallback
	}
	return alpha2ToFlag(code);
}
